openapi: 3.0.0
info:
    title: Twelve Labs Video API
    version: 1.0.0
    description: API for uploading videos, retrieving metadata, and searching videos.
servers:
    - url: https://api.twelvelabs.example.com
paths:
    /videos:
        post:
            summary: Upload a new video
            description: Upload a video file along with associated metadata.
            requestBody:
                required: true
                content:
                    multipart/form-data:
                        schema:
                            type: object
                            properties:
                                file:
                                    type: string
                                    format: binary
                                    description: The video file to upload.
                                title:
                                    type: string
                                    description: Title of the video.
                                description:
                                    type: string
                                    description: A brief description of the video.
                                tags:
                                    type: array
                                    items:
                                        type: string
                                    description: List of tags associated with the video.
                            required:
                                - file
                                - title
            responses:
                "201":
                    description: Video uploaded successfully.
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Video"
                "400":
                    description: Invalid input provided.
        get:
            summary: List uploaded videos
            description: Retrieve a paginated list of uploaded videos.
            parameters:
                - in: query
                  name: page
                  schema:
                      type: integer
                      default: 1
                  description: Page number for pagination.
                - in: query
                  name: limit
                  schema:
                      type: integer
                      default: 10
                  description: Number of videos per page.
            responses:
                "200":
                    description: A list of videos.
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    videos:
                                        type: array
                                        items:
                                            $ref: "#/components/schemas/Video"
                                    total:
                                        type: integer
                                        description: Total number of videos available.
                "400":
                    description: Invalid pagination parameters.
    /videos/{videoId}:
        get:
            summary: Retrieve video details
            description: Get detailed metadata and status for a specific video.
            parameters:
                - in: path
                  name: videoId
                  required: true
                  schema:
                      type: string
                  description: Unique identifier for the video.
            responses:
                "200":
                    description: Video details retrieved successfully.
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Video"
                "404":
                    description: Video not found.
    /search:
        get:
            summary: Search for videos
            description: Search videos by metadata, tags, or AI-generated embeddings.
            parameters:
                - in: query
                  name: query
                  required: true
                  schema:
                      type: string
                  description: Search query string.
                - in: query
                  name: page
                  schema:
                      type: integer
                      default: 1
                  description: Page number.
                - in: query
                  name: limit
                  schema:
                      type: integer
                      default: 10
                  description: Number of results per page.
            responses:
                "200":
                    description: Search results.
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    results:
                                        type: array
                                        items:
                                            $ref: "#/components/schemas/Video"
                                    total:
                                        type: integer
                                        description: Total number of matching videos.
                "400":
                    description: Invalid search query.
components:
    schemas:
        Video:
            type: object
            properties:
                id:
                    type: string
                    description: Unique identifier for the video.
                title:
                    type: string
                    description: Title of the video.
                description:
                    type: string
                    description: A brief description of the video.
                tags:
                    type: array
                    items:
                        type: string
                url:
                    type: string
                    description: URL where the video file is stored.
                metadata:
                    type: object
                    description: Extracted metadata such as resolution, duration, etc.
                uploadDate:
                    type: string
                    format: date-time
                    description: Timestamp when the video was uploaded.
            required:
                - id
                - title
                - url
