apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
    name: twelve-labs-worker-podmonitor
    namespace: monitoring
    labels:
        release: prometheus-grafana
spec:
    namespaceSelector:
        matchNames:
            - default
    selector:
        matchLabels:
            app: twelve-labs-demo-video-processor
    podMetricsEndpoints:
        - port: metrics
          path: /metrics
          interval: 30s
