apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: myapp-servicemonitor
    namespace: monitoring
    labels:
        release: prometheus-grafana # This label must match what the Prometheus Operator expects
spec:
    selector:
        matchLabels:
            app: twelve-labs-demo-api # This should match the label on your application's Service
    endpoints:
        - port: http # This should be the port name in your Service definition that exposes /metrics
          path: /metrics
          interval: 30s
